Document: libpng
Title: Debian libpng Manual
Author: <insert document author here>
Abstract: This manual describes what libpng is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpng/libpng.sgml.gz

Format: postscript
Files: /usr/share/doc/libpng/libpng.ps.gz

Format: text
Files: /usr/share/doc/libpng/libpng.text.gz

Format: HTML
Index: /usr/share/doc/libpng/html/index.html
Files: /usr/share/doc/libpng/html/*.html
